title: "Heretic Slackware Wiki"
description: "Unofficial Hacks, Tips, and Tricks for Slackware Linux"
theme: jekyll-theme-hacker
 # You can choose a different theme if you like: jekyll-theme-cayman, jekyll-theme-minimal, or jekyll-theme-hacker.
